### ISSUE TITLE
FPS Drops

### ISSUE THREAD

**Issue by Digawen** [SLOKnightfall/BetterWardrobe#15] opened 2020-09-11 06:43 UTC
Unfortunately I have massive FPS drops with the latest version (1.7.3). (From normal ~90+fps to 20-15fps) Unfortunately no Lua errors. On version 1.7.2 everything is as usual. 

And yes I have many many addons installed and when I am back home tomorrow I will try to switch everything off and then on again one by one ;)

**Comment by MrEzorn** [comment] 2020-09-11 12:12
I had the same issue and I confirm that "Better Wardrobe and Transmog" was the cause. Solved by disabling this one.

**Comment by SLOKnightfall** [comment] 2020-09-11 20:55
Should be fixed in the 1.7.4 release

**Closed** 2020-09-11 20:54 UTC
