### ISSUE TITLE
ElvUI Issue (Similar to 251)

### ISSUE THREAD

**Issue by NZephyr** [SLOKnightfall/BetterWardrobe#256] opened 2022-04-07 07:54 UTC
The visual conflict shown in closed issue #251 is still occurring on the Appearances tab (the Dressing Room issue is resolved) when using ElvUI. This didn't occur on a previous version of BetterWardrobe, but I cannot recall what version, and I haven't been able to find it in my saved files.

The image in issue #251 is exactly like what it looks like to me, so I haven't reuploaded another image. 

Please let me know if you need any information, or if there's a log somewhere I can get you (not sure what you'd need!).

**Comment by Tiburan** [comment] 2022-04-30 07:10
I can confirm this, however in my case it can be resolved by disabling Arkinventory, Rarity and Soulshape journal. 
I have no idea if these are any AddOns you use as well?

**Comment by NZephyr** [comment] 2022-04-30 14:26
I do use Rarity, and disabling it does seem to improve this. The color picker seems to still be misaligned. I will get screenshots later tonight to better compare. It could also be intended to look like that (the Rarity-disabled look).

**Comment by Beet4** [comment] 2022-08-20 21:19
I can confirm that there seems to be a compatibility issue between the ElvUI Skin of Better Wardrobe and Rarity.

This is how Better Wardrobe looks with no addons enabled except itself:
![image](https://user-images.githubusercontent.com/38279393/185766155-15f0ffa9-68ef-462f-bb44-18d74a8775d4.png)

With ElvUI Enabled, seems pretty much OK except for misaligned dropdown menu for sorting order and select color wheel:
![image](https://user-images.githubusercontent.com/38279393/185766214-a1e3cd78-daeb-42fe-99d0-5f2cf81e0d84.png)

And this is how it looks when I enable Rarity addon, this seems to break the ElvUI skin integration completely (and even more misaligntment):
![image](https://user-images.githubusercontent.com/38279393/185766257-7804337a-916c-4f9a-83ff-f46ced09a639.png)

It breaks on all tabs of Better Wardobe:
![image](https://user-images.githubusercontent.com/38279393/185766275-59ca7575-aeac-4f1e-9ef5-137554c68f34.png)

![image](https://user-images.githubusercontent.com/38279393/185766278-0b4d7067-907d-4b8e-9eda-2ce0243e5c73.png)

![image](https://user-images.githubusercontent.com/38279393/185766284-2cc987db-c5cd-4955-87a0-41df192b2a7d.png)

@SLOKnightfall would you mind taking a look why the ElvUI integration breaks in combination with Rarity whenever you have time? Thanks! :)

**Comment by Tiburan** [comment] 2022-08-21 06:14
@Beet4 

Could you do me a favor, could you please check if you get the same outcome with Arkinventory? Just want to be sure it is not a corrupted saved_variable on my end.  (even though I removed the WTF folder and tried fresh copies of everything)
I would just be nice if there was another case but mine. 
To be clear, ElvUI, Better Wardrobe and Arkinventory. 

Thank you in advance.

**Comment by Beet4** [comment] 2022-08-21 21:01
@Tiburan 

ElvUI + Better Wardrobe Only:
![image](https://user-images.githubusercontent.com/38279393/185810705-c5a20d14-c473-4037-a481-cec607725412.png)

ElvUI + Better Wardrobe + ArkInventory (no other addons enabled):
![image](https://user-images.githubusercontent.com/38279393/185810749-57d62d5c-11cd-4689-a06d-b9826f5d2fc3.png)

Confirms the issue also effects the combination ElvUI + Better Wardrobe + ArkInventory.

**Comment by Tiburan** [comment] 2022-08-22 06:16
@Beet4 

Thank you very much for taking the time / effort to test and confirm.

**Comment by ellaerror** [comment] 2022-10-09 01:03
Hi, I found a solution to this issue. In Plugins/ElvUI.lua of BetterWardrobe there's this code on line 505:
```lua
if not IsAddOnLoaded("Blizzard_Collections") then
	LoadAddOn("Blizzard_Collections")
	C_Timer.After(2, UpdateCollectionFrames)

end
```

By changing the code to this:
```lua
if not IsAddOnLoaded("Blizzard_Collections") then
	LoadAddOn("Blizzard_Collections")
		
end
		
C_Timer.After(2, UpdateCollectionFrames)
```
the issue no longer happens, at least for me. I believe this is because rarity gets loaded first and they also load the addon "Blizzard_Collections" (Rarity/Core/Collections.lua). By doing this, the function `IsAddOnLoaded("Blizzard_Collections")` returns `true`, which causes the `UpdateCollectionFrames` to never be called. I hope this helps.

* commented this on the wrong issue at first, lol

**Comment by Beet4** [comment] 2022-10-10 13:58
Great! Hope this can be implemented in a future release then. :)

**Comment by NZephyr** [comment] 2022-10-28 04:43
Thank you for the info! Sorry I didn't comment beforehand, I'd kinda forgotten I'd posted this until Monday, and basically decided that 10.0.0 would break things anyway, which it did, ha! After the current issue I recently posted is resolved to allow it, I'll check to see if this solution still works for me!

**Comment by SLOKnightfall** [comment] 2022-10-28 16:56
The fix has been added to the 4.1.1 release.  Thanks for finding the solution and for taking so long to implement.

**Comment by Beet4** [comment] 2022-10-28 20:27
So the fix in 4.1.1 worked for a bit but it randomly stopped working again? With the following LUA Error:
`3x Interface/AddOns/BetterWardrobe/Plugins/ElvUI.lua:120: attempt to index local 'WardrobeCollectionFrame' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Plugins/ElvUI.lua"]:120: in function <Interface/AddOns/BetterWardrobe/Plugins/ElvUI.lua:117>

Locals:
WardrobeCollectionFrame = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 L_UIDropDownMenuSkinned = true
 Blizzard_Channels = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Channels.lua:7
 TalkingHead = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/TalkingHead.lua:110
 HandleFrame = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:129
 ArrowRotation = <table> {
 }
 HandleNextPrevButton = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1054
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceTimer-3.0/AceTimer-3.0.lua:147
 QuestFrameProgressItems_Update = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Quest.lua:337
 GuildInviteFrame = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Guild.lua:217
 MirrorTimers = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/MirrorTimers.lua:6
 Ace3_ColorizeEnable = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Ace3.lua:512
 AlertSystem = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Alerts.lua:787
 HandleIcon = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:992
 Blizzard_WeeklyRewards = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/WeeklyRewards.lua:65
 SetDisabledBackdrop = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:234
 HandleCategoriesButtons = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:76
 Blizzard_PlayerChoice = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/PlayerChoice.lua:107
 ADDON_LOADED = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1748
 HandleSliderFrame = <function> defined =[C]:-1
 SkinTalentListButtons = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:360
 HandleEditBox = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:794
 TutorialFrame = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/TutorialFrame.lua:6
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceHook-3.0/AceHook-3.0.lua:273
 RegisterSkin = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1783
 DressUpFrame = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/DressingRoom.lua:49
 Blizzard_AnimaDiversionUI = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/AnimaDiversion.lua:6
 HandleFollowerListOnUpdateDataFunc = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1362
 SkinDoubleStateIconRow = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1702
 HandleTrimScrollBar = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:634
 SkinWidgetContainer = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1741
 HandleCheckBox = <function> defined =[C]:-1
 UnregisterAllEvents = <function> defined @Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 Blizzard_ItemInteractionUI = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/ItemInteraction.lua:6
 ScriptErrorsFrame = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Debug.lua:86
 Blizzard_Calendar = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Calendar.lua:44
 SkinCaptureZone = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1711
 EarlyAceWidgets = <table> {
 }
 Blizzard_DebugTools = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Debug.lua:92
 QuestFrame_SetTitleTextColor = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Quest.lua:342
 name = "ElvUI_Skins"
 Blizzard_CovenantSanctum = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/CovenantSanctum.lua:50
 SkinIconTextAnd`

![image](https://user-images.githubusercontent.com/38279393/198726380-750b928d-cc34-446e-b202-0d54212652bc.png)

**Comment by Beet4** [comment] 2022-10-28 20:33
Seems like it only happens on initially loading into the game after booting it up. If you do a /reload there is no LUA error and the skin works.

**Comment by SLOKnightfall** [comment] 2022-10-28 20:34
Thanks. I'll look into it

**Comment by Beet4** [comment] 2022-10-29 10:23
So skin seems to be at least loading now even with Rarity enabled which just got an update for 10.0 so that is good. However there are some new visual bugs, I'll post them in this issue as it's probably ElvUI related.

Dropdown in the transmogrify window is sometimes very wide:
![image](https://user-images.githubusercontent.com/38279393/198825679-c776bd03-065e-4097-9243-f3f254f715ee.png)

When it's not save button seems to overlap with the buttons a bit:
![image](https://user-images.githubusercontent.com/38279393/198826091-cddec863-2df8-4f43-a2cd-dcf3ae79e7e0.png)

The last Saved sets button overlaps with the progress bar in the transmogrify window:
![image](https://user-images.githubusercontent.com/38279393/198825695-e9b31d3b-ab52-4d6c-90a9-e2b3e85e7e07.png)

As well on the appearance tab:
![image](https://user-images.githubusercontent.com/38279393/198825711-daf8c1e2-7537-4b02-9ea8-049d5c0a2a2c.png)

This one is really weird in the appearance window, happens more often than not. If it happens it seems to happen every time I open the window in the same session, a reload might help:
![image](https://user-images.githubusercontent.com/38279393/198825724-31a975b1-c13f-4bbe-9960-ccd8ef4ac028.png)

Fullscreen screenshot of the transmogrify just for the sake of it:
![image](https://user-images.githubusercontent.com/38279393/198825890-0e7d47a1-97a1-424c-9b9a-5b93d9534140.png)

Fullscreen screenshot of the appearance window just for the sake of it:
![image](https://user-images.githubusercontent.com/38279393/198825893-d8dc12ac-edfc-4856-ba26-870bc44a6273.png)

Really appreciate the hard work you are doing with the awesome addon <3

**Comment by SLOKnightfall** [comment] 2022-11-05 19:47
The next update has the elvui skin reworked and should fix this

**Closed by SLOKnightfall** 2022-11-05 19:47 UTC
