### ISSUE TITLE
Is there a chance you could provide releases on your GH page?

### ISSUE THREAD

**Issue by schwim0341** [SLOKnightfall/BetterWardrobe#257] opened 2022-04-10 14:00 UTC
For those of us that use WoWUp, is there a chance you could provide releases with the correlating zip file?  I'm trying to purge all curse links and I'm unable to for any addons that don't show up in other repos(like wowinterface) or on github as a release.

Thanks for your consideration!

**Comment by SLOKnightfall** [comment] 2022-04-10 18:46
It is on my list of things to do.  Unfortunately it currently uses curseforge's packager so I just need the time to figure out and implement a solution to change that.

**Comment by JVemmer** [comment] 2022-09-28 12:55
Potential duplicate of #250.

**Comment by SLOKnightfall** [comment] 2022-10-28 20:23
The addon is now set to create packaged releases and is also being hosted on wago.io   https://addons.wago.io/addons/betterwardrobe

**Closed** 2022-10-28 20:23 UTC
