### ISSUE TITLE
Scrolling set or extra lists causes lag if bagnon is enabled

### ISSUE THREAD

**Issue by Taurmin** [SLOKnightfall/BetterWardrobe#338] opened 2023-01-24 06:48 UTC
I am having a perculiar issue where scrolling the list of sets, either wow's own "sets" list or BW's "Extra" list will cause the whole game to lag. Disabling Bagnon seems to mitigate this for some reason.

The issue only occurs with BW enabled, bagnon does not seem to interfere with the build in "sets" list on its own.

**Comment by n1ckal** [comment] 2023-02-28 11:39
Exactly the same issue here - and it makes your addon unusable. Literally unusable.

**Comment by SLOKnightfall** [comment] 2023-04-29 20:45
Well it took a while but I finally managed to track down the cause of the lag when Bagnon is enabled.   Bagnon hooks into the TooltipDataProcessor, so every time a tooltip is shown Bagnon tries to look up how many of the item a player has and adds that info to the tooltip.  BetterWardrobe uses hidden tooltips to look up class data for the sets window.  So when scrolling Bagnon is queuing up a bunch of lookups which is causing the lag.   A partial fix is that I've added a cache for the data from the tooltips, so after the initial lookup BetterWardrobe can use the cache eliminating Bagnon from triggering multiple lookups and causing some lag.  Unfortunately there is still going to be some initial lag, but once things get caches the lag should stop.  Additionally I found a few places where things were not getting cached properly and fixed them, so that hopefully should clear up some of the non Bagnon lag.

**Comment by SLOKnightfall** [comment] 2023-04-30 20:56
Figured out how to parse the tooltip data I need with out having to set the tooltip. This will prevent the triggering of the Bagnon's lookups and should get rid of a bunch of the lag.

**Comment by SLOKnightfall** [comment] 2023-04-30 22:37
Should be fixed in release 4.10

**Closed by SLOKnightfall** 2023-04-30 22:37 UTC

**Comment by Taurmin** [comment] 2023-04-30 23:21
Awesome that you found the reason, sounds like an exilirating but of troubleshooting.
