### ISSUE TITLE
copy to clipboard bugged

### ISSUE THREAD

**Issue by Goten87** [SLOKnightfall/BetterWardrobe#345] opened 2023-02-02 16:43 UTC
i get this error when i try to copy a set in the dressing room with only this addon on (if i have more it gives a other addon as the couse but when i disable this addon it works again for all the other addons)
![image](https://user-images.githubusercontent.com/1938598/216387023-b418248d-10fb-4cc4-8ebd-4590dfbafe13.png)

steps to reperduce:
inspect someone
open in dressing room
try to copying it

**Comment by TheLastDarkthorne** [comment] 2023-03-05 10:25
I'm also getting this issue
Here is what BugSack shows:

```
2x [ADDON_ACTION_FORBIDDEN] O Addon 'BetterWardrobe' tentou chamar a função protegida 'CopyToClipboard()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `CopyToClipboard'
[string "@SharedXML/DressUpModelFrameMixin.lua"]:60: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>
```

**Comment by TheLastDarkthorne** [comment] 2023-03-05 10:26
'Export Set' option also doesn't seem to be working although it is not firing any errors that I could see

**Comment by SLOKnightfall** [comment] 2023-09-26 23:52
I think I finally found out the cause and it should be fixed in the next update,

**Closed by SLOKnightfall** 2023-09-26 23:52 UTC
