### ISSUE TITLE
"Sort by:" drop down menu on top of appearances 

### ISSUE THREAD

**Issue by pesrou** [SLOKnightfall/BetterWardrobe#458] opened 2024-08-02 04:08 UTC
Title basically, the drop down menu sits on top of the first row of items displayed.
Image for reference:
![Screenshot 2024-08-02 010355](https://github.com/user-attachments/assets/8415b474-f5f5-43ae-915c-32923e21b469)

**Comment by SLOKnightfall** [comment] 2024-08-03 17:26
Fixed in next update.  Was caused by old ElvUI code

**Closed by SLOKnightfall** 2024-08-03 17:26 UTC

**Comment by pesrou** [comment] 2024-08-03 17:32
Resourceful as always, sorry about the duplicate!
Cheers mate
