### ISSUE TITLE
4.2 breaks ElvUI skinning of Collections tab

### ISSUE THREAD

**Issue by DJScias** [SLOKnightfall/BetterWardrobe#298] opened 2022-11-05 20:37 UTC
Hello there,

Not sure if this was intended, but the fix that was done in https://github.com/SLOKnightfall/BetterWardrobe/commit/8d68dd58b5297aa59afd84796784bc81f3699e10 seems to disable the ElvUI skinning on all of the collections tabs.
![image](https://user-images.githubusercontent.com/439655/200140323-2d27be85-f200-41c8-a8a9-e2120e7c6347.png)
![image](https://user-images.githubusercontent.com/439655/200140330-5b37dad6-3624-4748-82b1-5911a2ace252.png)

Disabling BetterWardrobe makes the skinning works once more.

**Comment by SLOKnightfall** [comment] 2022-11-07 20:16
Can you check that you have the Collection skin enabled in Elvui as disabling that setting is the only way I can reproduce what you are seeing with the Appearances tab being skinned and the other tabs using the Defaut UI.   If you are trying to get the Appearance section to use the default Blizzard UI you need to disable the Elvui Transmog skin since the Appearance frames are shared between the Collection Journal and the Transmog Vendor UI

**Comment by SLOKnightfall** [comment] 2022-11-07 21:13
Should be fixed in the next update

**Closed** 2022-11-07 21:15 UTC
